### ISSUE TITLE
Setup coding standard

### ISSUE THREAD

**Issue by TomasVotruba** [petrvacha/rednoi#2]
I think this awesome repo would deserve propper CI checked coding standard. 

I can came to Brno personally and help you with that personally in some Tea House.

What do you think?

**Comment by petrvacha** [comment]
Hi Tom, thank you for your interest! That sounds very good. What about today? Are you free?

**Comment by TomasVotruba** [comment]
Yes, that is awesome Peter. I will come immediately!

**Comment by TomasVotruba** [comment]
I'm on my way!

![image](https://user-images.githubusercontent.com/924196/28238934-4ec576f0-695f-11e7-8d0e-31c164487950.png)
